on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

permissions:
  contents: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: 安卓模拟自动注入 ${{ github.ref }}
      #     body_path: README.md
      #     draft: false
      #     prerelease: false
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: README.md

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
          cache-dependency-path: | # optional
            sub-project/*.gradle*
            sub-project/**/gradle-wrapper.properties
      - name: Setup Gradle 7.3.3
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '7.3.3' # Quotes required to prevent YAML converting to number
      - name: Publish package
        env:
          ACCESS_USER: ${{ secrets.ACCESS_USER }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_PERSONAL_ACCESS_TOKEN: ${{ secrets.ACCESS_PERSONAL_ACCESS_TOKEN }}
        run: |
          gradle app:AutoWired:build
          gradle app:AutoWired:publish
